### ISSUE TITLE
Incompatible with gnome shell 42

### ISSUE THREAD

**Issue by Klewerro** [Moon-0xff/gnome-mpris-label#1]
Plugin at [gnome.extentions.org](https://extensions.gnome.org/extension/4928/mpris-label/) is incompatible with Gnome Shell 42 (Manjaro, shell version 42.4).
I forced installing incompatible extensions by command `gsettings set org.gnome.shell disable-extension-version-validation true`, and after few days of using plugin, I didn't noticed any bugs or issues.

Please consider test and raise up compatibility version, because it's very useful and straight forward plugin :+1:

**Comment by Batwam** [comment]
works fine with Gnome 43 by disabling the version check.

**Comment by Moon-0xff** [comment]
Good to know, thanks to both of you for testing my extension. Gonna bump the version soon!

**Comment by Batwam** [comment]
updated compatibility included in pull request #3 for good measure

**Comment by Moon-0xff** [comment]
Uploaded the extension with explicit support for 42 and 43 to extensions.gnome.org
I'm going to close this thread when the "new" version gets accepted.

**Comment by Moon-0xff** [comment]
Looks like the "new" version got accepted, Closing this thread.
