### ISSUE TITLE
Feature request: double-click mouse bindings

### ISSUE THREAD

**Issue by cabe7** [Moon-0xff/gnome-mpris-label#103]
Nice extension. It would be very useful if actions could be assigned to double clicks (primarily left / right / middle). Currently, for mice without a thumb button it's not possible to fully control the player directly from the extension.

**Comment by Moon-0xff** [comment]
Hello @cabe7  
This is already a feature, added on version 23 of the extension, #73

If you don't see the options for double clicks you are probably running a version lower than 23.
  
Here's the settings panel with the double clicks options (borrowing it from #100): ![Screenshot from 2024-04-28 16-53-27](https://github.com/Moon-0xff/gnome-mpris-label/assets/76393980/f36617fc-38c2-4655-9df7-6e6857d6086d)
