### ISSUE TITLE
Gnome 47 support?

### ISSUE THREAD

**Issue by DeN-AlB** [Moon-0xff/gnome-mpris-label#108]
I just installed Gnome 47 in Arch (EndeavourOS) and the extension is not working anymore.

Are you working on an update for Gnome 47, already? Would be great to help you to support it, like I did for Gnome 46. 😉

**Comment by DeN-AlB** [comment]
Modified the `metadata.json` and everything looks fine. Seems, that there are no issues with Gnome 47. :+1:

**Comment by Moon-0xff** [comment]
> Modified the metadata.json and everything looks fine. Seems, that there are no issues with Gnome 47. 👍

47 didn't introduce changes that could interfere with the extension as far as I know, so that's probably the only thing needed. I pushed a commit to modify `metadata.json` and I'll update the extension on ego soon enough.

Sorry for the wait for such an easy update 😅  I don't check this repository too often anymore (#88).  
If you are interested, I could give you a quicker way of letting me know if Arch bumped it's Gnome version, just send me an email about it (`moon-0xff [at] protonmail.com`).

**Comment by DeN-AlB** [comment]
> I'll update the extension on ego soon enough.

Take your time. Thank you very much. ;)


> Sorry for the wait for such an easy update 😅 I don't check this repository too often anymore (#88).

No problem for me. If modifying the `metadata.json` is the only thing that is needed to get the extension to work, I would do so. But I try to remember your email and will ping you, if an update is needed. Thanks. :+1:

**Comment by Batwam** [comment]
For those who don't want to have to modify the extension, I believe that you can also disable the version verification:
`gsettings set org.gnome.shell disable-extension-version-validation true`

**Comment by DeN-AlB** [comment]
But disabling the setting will disable the verification for all extensions. Just wanted to mention. ;)

**Comment by Batwam** [comment]
Indeed, there is unfortunately no way to disable for a single extension unfortunately

**Comment by Moon-0xff** [comment]
No worries! The new version was accepted on ego, so Gnome 47 users don't need a workaround anymore.  

> But I try to remember your email and will ping you

Not quite, I don't check that e-mail often either, but I can give you a way of contacting me quicker if you send me a mail about it (well, I need to send *you* an e-mail, but I can only know your address if you send something first 😝).

**Comment by DeN-AlB** [comment]
Got it. :+1:

**Comment by Moon-0xff** [comment]
@DeN-AlB I sent you the stuff about contacting me quickly.
And I think I've done everything that needs to be done after a new version release now, so that wraps it up.

Thanks for raising the issue @DeN-AlB, and @Batwam too!
