### ISSUE TITLE
Gio.js Warning: Too many arguments

### ISSUE THREAD

**Issue by Moon-0xff** [Moon-0xff/gnome-mpris-label#15]
The extension writes to journalctl this warning from time to time:
```
JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
```
You can trigger this by disabling the extension and enabling it again with an mpris source active.

**Comment by Batwam** [comment]
looks like this is a bug in Gio.js which should be resolved upstream shortly: https://bugs.launchpad.net/ubuntu/+source/gjs/+bug/1988393

https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/790

**Comment by Moon-0xff** [comment]
Solved. No idea when though 😅

**Comment by Batwam** [comment]
I guess that still counts as a win!
