### ISSUE TITLE
Remove info when no music is playing

### ISSUE THREAD

**Issue by Batwam** [Moon-0xff/gnome-mpris-label#2]
Hello,

Amazing extension, I love it. Would it be possible to remove the text when the music isn't playing (ie paused)? Perhaps as an option? I note that the following command allows to check if the music is playing or not (in spotify in this example) `gdbus call --session --dest org.mpris.MediaPlayer2.spotify --object-path /org/mpris/MediaPlayer2 --method org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player PlaybackStatus`

**Comment by Moon-0xff** [comment]
It was an intended feature at some point. Probably had some trouble implementing it.

**Comment by Batwam** [comment]
#3 looks like it's possible. I've just had a go at it and it seems to work fine. Full disclosure, I have no experience with javascript, D-Bus calls or gnome extensions so, this may not be the prettiest implementation but it sure seems to work, maybe it will point you in the right direction :-)

**Comment by Moon-0xff** [comment]
#3 was merged to main
