### ISSUE TITLE
Shell crashes when changing settings

### ISSUE THREAD

**Issue by Moon-0xff** [Moon-0xff/gnome-mpris-label#36]
`JS object wrapper for GObject 0x560283d7a0d0 (GSettings) is being released while toggle references are still pending.`

Happens when typing fast.

**Comment by Moon-0xff** [comment]
Bad luck! Merging this broke the pref window for GNOME 44. I did also tried to crash the window without luck. @Batwam have you experienced these crashes? Can you test if not? Just type fast at random in the ignore list.

**Comment by Batwam** [comment]
Let me check that now

**Comment by Moon-0xff** [comment]
Using the previous head though! `git checkout HEAD^`

**Comment by Batwam** [comment]
The pre-#41 merge then right? I haven't updated my fork so I don't have the #41 commit yet. I can test then.

**Comment by Batwam** [comment]
I have to say I never experienced this issue. I just tried the type fast in Gnome 44 using pre-#41 from `main` in my fork and still no crash. You might want to revert then.

What issue are you getting in Gnome 44 post-merge?

**Comment by Moon-0xff** [comment]
I can't seem to replicate the bug now! Except when changing the icon option really fast which isn't surprising. Not really sure why though, maybe e563813ecb67e0a096a6b69a3ddccc5dd2828633 fixed the issue? I'm pretty sure I've experienced crashed after e563813ecb67e0a096a6b69a3ddccc5dd2828633, maybe I'm misremembering? In any case ffec27099904b4ed7ce378160fc38c2a9c237330 needs to be reverted.

the `focus-out` signal doesn't exists in GNOME 44 for some reason (at least that's the error).

**Comment by Batwam** [comment]
Yeah, ok. I think that the more "fancy" bindings we put in, the more maintenance we are likely to get in the future so less is probably more if it's not really an issue.

**Comment by Moon-0xff** [comment]
The reason why i raised this issue was because the bug was painfully frequent, but looks like indeed https://github.com/Moon-0xff/gnome-mpris-label/commit/e563813ecb67e0a096a6b69a3ddccc5dd2828633 solved the issue, so that's good.

How's the extension working for you? Have you tested it in that VM with countless players? Thinking of releasing the new version soon.

**Comment by Batwam** [comment]
I haven't checked for a while as that VM stopped booting for some reason but I'll install a few players in gnome-nightly later this weekend and confirm. Pretty sure it will be fine.

**Comment by Moon-0xff** [comment]
Yes, i have the same thought, at the same time we stacked quite a bit of changes since last release so there's a lot of new places where the extension could possibly break.

**Comment by Moon-0xff** [comment]
Closing this and reverting last commit.
