### ISSUE TITLE
play/pause not working with Rhythmbox when playing radio stations

### ISSUE THREAD

**Issue by sebo505** [Moon-0xff/gnome-mpris-label#48]
Have set right mouse klick to toggle play/pause.
Works with Rhythmbox when playing podcast.
Works with Rhythmbox when playing music from local library.
Works NOT with Rhythmbox when playing radio streams.

Have noticed that Rhythmbox itself shows stop button instead of pause button when playing radio.

Any way to make toggle play/pause(stop) working in this case never the less?

![Bildschirmfoto vom 2023-04-18 22-00-00--#bug_#Gnome_Extension_#Mpris_Label](https://user-images.githubusercontent.com/65250211/232893255-254156a0-63af-4c79-a488-297b3a2b3e39.png)

**Comment by sebo505** [comment]
Sounds great. Much appreciated !!!

**Comment by Moon-0xff** [comment]
Change committed, Indeed it was an easy and straight forward fix.

If you want to get the fix early you can follow the [instructions on the readme](https://github.com/Moon-0xff/gnome-mpris-label/blob/main/README.md) to install the development version.

**Comment by Moon-0xff** [comment]
New version is out, with the fix for this included.
Thanks for raising this issue!
