### ISSUE TITLE
how can i change binding to the scroll up and down to next and previous track if i dont want volume control

### ISSUE THREAD

**Issue by slaygun** [Moon-0xff/gnome-mpris-label#49]

**Comment by Moon-0xff** [comment]
**Currently isn't possible to rebind the scroll up/down actions.**

The mouse scroll doesn't returns a simple *click event* that we can detect and use to activate the various actions, instead it returns a *value* and that value, and how often is returned varies widely from one device to the next.  
So we can't translate easily between these events and click actions.

But for sure we want to add this in the future, no plans to do it soon though.

**Comment by Moon-0xff** [comment]
Some mice have two extra side buttons where your thumb rests (if you use your mouse right handed), [Like this one.](https://upload.wikimedia.org/wikipedia/commons/2/23/Logitech_corded_mouse_m500_imgp1410_smial_wp.jpg)

If you lack the extra buttons and don't want to rebind others the best solution would be to assign a keyboard shortcut:  
Settings -> Keyboard Shortcuts -> Previous Track / Next Track

Note that gnome isn't aware of the player selection in the extension, I think the first spawned player is always the one with the controls.
