### ISSUE TITLE
G4Music Compatibility

### ISSUE THREAD

**Issue by Batwam** [Moon-0xff/gnome-mpris-label#53]
FYI, [G4Music](https://flathub.org/apps/com.github.neithern.g4music) will show with a full address in the menu. 
This is due to the fact that the `Identity` field isn't populated correclty. I have reported it inthe G4Music gitlab: https://gitlab.gnome.org/neithern/g4music/-/issues/72

![image](https://user-images.githubusercontent.com/56710655/236653721-f6c574d8-bce6-45e1-ba3a-6fc006f24245.png)

Play/Pause, Next, Previous, etc works fine but `open app` doesn't open the window and the icon also isn't found, most likely as a byproduct of the issue above although the `.desktop` based search fallback should work as `DesktopEntry` does match the .desktop filename.

**Comment by Batwam** [comment]
Interestingly enough, the Volume Levels utility in Settings gets the app name correct again: 
![Screenshot from 2023-05-07 16-35-58](https://user-images.githubusercontent.com/56710655/236667016-80c24336-5dec-403f-ab7c-c9863344156e.png)

**Comment by Moon-0xff** [comment]
G4Music's maintainer already pushed a fix for this! 😄

**Comment by Batwam** [comment]
nice. should we leave this open until the flatpak is updated and we can confirm that this fixes the menu and icon?

**Comment by Moon-0xff** [comment]
Yes, it might be a good idea to keep issues open until fixes are released. But in any case a new version of G4Music with the fix included is already out.

**Comment by Batwam** [comment]
flatpak update confirmed and issue resolved, including volume control: 
![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/56710655/4fe689f3-96ad-4337-8885-82bdb71e5b76)
