### ISSUE TITLE
Add sliders

### ISSUE THREAD

**Issue by abisammy** [Moon-0xff/gnome-mpris-label#63]
This was touched upon in https://github.com/Moon-0xff/gnome-mpris-label/pull/59, however it was decided not to add it for the specific feature due to a lack of consistency. 

I believe adding sliders across the entire extension will make the settings more intuitive to use, please let me know what you think.

It changes a simple number to:
![image](https://user-images.githubusercontent.com/75337261/242062031-b8575838-ba89-4b7e-ad6c-a1bf5236e236.png)

**Comment by Moon-0xff** [comment]
Sliders are a good fit for certain options, but the current design of the prefs window is column based, sort of like a spreadsheet.  
I don't think sliders are good fit for it, specially because GTK4 gives a very flat look to the `Gtk.Notebook` widget.

**Comment by Moon-0xff** [comment]
I want to experiment with the design of the prefs window after removing GTK3 compatibility (#62)

Specifically, I want to *visually merge* some options and make the prefs window look less like an spreadsheet, but at the end of the day I don't think we can justify the added complexity of prettier options.

**Comment by abisammy** [comment]
Issues mentioned in: https://github.com/Moon-0xff/gnome-mpris-label/issues/67
