### ISSUE TITLE
System slowdown with some Apps

### ISSUE THREAD

**Issue by Batwam** [Moon-0xff/gnome-mpris-label#7]
As reported in a recent comment, some people appear to be experiencing system freezes when the extension is active which go away when turned off:

- e.g.: https://apps.gnome.org/app/de.haeckerfelix.Shortwave/
- I see that some apps seem to struggle with Mpris including Rhythmbox: https://github.com/solus-project/budgie-desktop/issues/794

I wonder if other similar has the same issue. If not, it would be worth checking why not and if they have implemented any workaround. 

It would also be good to know if previous versions of the extension experience the same thing and how much increasing the refresh-rate improve things. 

Ultimately, updating text/icon only upon change would be preferred.

**Comment by Moon-0xff** [comment]
v3 (bffdcd46f4ff7bb286deb8970df80b0e94532570) + Shortwave doesn't freezes the shell. Or at least it isn't too noticeable.

**Comment by Moon-0xff** [comment]
The dBus handling code of [mpris-indicator-button](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/blob/master/mprisindicatorbutton%40JasonLG1979.github.io/dbus.js) includes some error checking among other things. We should check if Shortwave works fine with this extension.

**Comment by Moon-0xff** [comment]
Yes, mpris-indicator-button works fine with Shortwave.

**Comment by Moon-0xff** [comment]
[Based on the latest comment on ego](https://extensions.gnome.org/extension/4928/mpris-label/?c=137841) (not mine obviously) it looks like the shell freezes for the amount of time D-Bus gives [until timeout](https://github.com/solus-project/budgie-desktop/issues/794#issuecomment-929718207) with certain applications.

**Comment by Moon-0xff** [comment]
All the applications mentioned are somewhat related to GNOME. can it be a problem with glib, gtk or another GNOME toolkit?

**Comment by Batwam** [comment]
Yeah, it's pretty odd. I just tried Videos/Totem and I can't seem to experience anything. Shortwave is somewhat noticeable with some stutter every time it refreshes.

I think that the best thing to do will be to figure out which specific calls are causing the slowdowns to avoid focusing on the wrong parts.

I have a couple of ideas which might help reduce the number of dbus calls but for initial troubleshooting it would be good to monitor response times over the various dbus calls to understand what is hanging.

Is anyone getting freezes during first source app launch and then it works fine?

Did we say that other similar extensions are fine?

**Comment by Batwam** [comment]
ok, I think that we should tackle this issue next. I have [some ideas](https://github.com/Batwam/gnome-mpris-label/tree/speed-test) to reduce some of the calls without affecting the way the extension currently works but I'll let close you the install instructions first to avoid having multiple pull requests open in parrallel.

**Comment by Batwam** [comment]
ok, I've tried to check the time taken for the various DBus calls throughout the code in the "speed-test" branch and I think that the results speak for themselves:
![image](https://user-images.githubusercontent.com/56710655/205433487-e147121f-9964-48b9-803f-c9d17aca8500.png)

**Comment by Moon-0xff** [comment]
Good detective work, but i don't think any of those changes will solve the problem.

Don't worry about having multiple pull requests active, specially because they don't collide with each other in any way.

I will be making changes to the D-Bus related code and pushing them to the `dbus-changes` branch, you might want to sync your branch to this one.

**Comment by Batwam** [comment]
Yeah, ultimately the response time is too long so it hangs. If we could take that down to the same level as the others the lack of optimisation would be less noticeable or drastically reduce the number of requests by making it asynchronous.

What other solution do you have in mind? Have you found a way to get dbus to notify the extension of the changes?

**Comment by Moon-0xff** [comment]
Correct me if I'm wrong, but i don't think this concept of requests apply to async threads.

[MPRIS notifies property changes through a signal](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html)

**Comment by Batwam** [comment]
well, that's the million dollar question but I was thinking the same when you first sent me this link. These commands are the same we are currently using. I don't know if you have a fancy solution in mind but at the most simplistic level, we would need a way to get notified of a change in the mpris data we are interested in (i.e change in song metadata string, playbackStatus where relevant), and then we would run the same commands we are currently running.

**Comment by Moon-0xff** [comment]
Basically. [Check the async programming guide.](https://gjs.guide/guides/gjs/asynchronous-programming.html#the-main-loop)

**Comment by Batwam** [comment]
yeah, I'm not sure to be honest, I'd need to see it being implemented to understand. Have you seen any extension using this?

This looks similar to interrputs in C but at the end of the day, we would still need to find out when the active source has changed and extract the metadata from the sources so, unless I'm missing something, the bulk of the current code (and associated slow DBUS calls) should still apply but hopefully much more rarely (only when a change is detected rather them several times per second...)? or you are hoping to be running these mpris data requests in parrallel to the main loop and that would avoid slowdowns?

**Comment by Moon-0xff** [comment]
Javascript is a single-threaded language. The shell is written in javascript. [Extensions are part of the shell once enabled](https://gjs.guide/extensions/overview/architecture.html#extensions).
So if our extension stops, the entire shell stops.

using a different process thread to handle events will avoid this. The same way as when a program freezes, it doesn't freezes the entire computer (most of the times).

That's how i understand it at least. I'm not used to async programming.

**Comment by Batwam** [comment]
Sounds like a different version of the extension altogether. There is a thread about async extension here, perhaps some example code to use as a starting point: https://stackoverflow.com/questions/67411285/asynchronous-extension-breaks-gnome-shells 

In the meantime, I might still push some simple optimisations to the current implementation to improve the workflow.

**Comment by Moon-0xff** [comment]
> In the meantime, I might still push some simple optimisations to the current implementation to improve the workflow if that's ok.
Sure, go ahead!

**Comment by Batwam** [comment]
ok, work in progress code is here: #11 
it would be great if you could help splitting getMetadata so it only runs once per cycle. I tried to do it myself but couldn't get it to work.

**Comment by Moon-0xff** [comment]
> Sounds like a different version of the extension altogether. Not sure how quickly that can be put together.

Yes, I'm starting from scratch. I don't know how much time this will take but probably several weeks. Perhaps I'm too ~~optimistic~~ pessimistic.

**Comment by Batwam** [comment]
Issue reported on the shortwave side. Hopefully we can address it on both sides as I still don't understand why it's taking `shortwave` so much longer: https://gitlab.gnome.org/World/Shortwave/-/issues/684

and yes, there might be other apps which would require fixing to.

**Comment by Moon-0xff** [comment]
I'm trying to build a tiny version of this extension capable of dealing with the slow responses of shortwave under the `minimal` branch.

I don't have much experience doing asynchronous programming, and i never done it in javascript, so this is more of a learning process than a development process.

**Comment by Batwam** [comment]
Hey, I checked out the `minimal` branch. It appears to be working (as long as I create a schemas folder for gsettings). The code doesn't look too different, is the plan to keep it minimal, or update the base code to match the async method (or maybe even both)?

One thing I noticed though is that if I run my highly scientific test of pressing a key and see if it hangs, I notice that it still hangs every second with shortwave. Obviously it's not as bad as the old extension which was running 4-5 dbus calls per cycle but it's still there. Did you notice that too?

**Comment by Moon-0xff** [comment]
Hello @Batwam, hope you are feeling well.
I noticed more than that, it looks like almost all the delay comes from redefining the player proxy. Check out the `structure-changes` branch and enable the time logs.

**Comment by Batwam** [comment]
Yeah, feeling a but better now, thanks!

I just checked out the other branch, very impressive indeed!

**Comment by Batwam** [comment]
I noticed that the icon padding on the right is no longer adjusted. when looking in more detail, I realised that the mechanism in `_onPaddingChanged(){` within `if(SHOW_ICON)` is ignored as we have the line `const SHOW_ICON = this.settings.get_int('show-icon');` as int while `show-icon` is a boolean. However, if I swap for `const SHOW_ICON = this.settings.get_boolean('show-icon');`, the extension no longer loads which is odd as it works just fine within `_setIcon()`...

**Comment by Moon-0xff** [comment]
Because constants can't be redefined. I pushed a fix just now, good catch.

**Comment by Moon-0xff** [comment]
So, as far as i know/tested #13 solves short-freezes, but what about long freezes? I know they are a thing because i have experienced them with rhythmbox before, it never occurred to me it was a problem with the extension though.

**Comment by Batwam** [comment]
Same here, I've experienced it exclusively with Rhythmbox but it hasn't occurred for a while. Somehow, I have the feeling that the latest changes might help this issue as a by-product. 

If the freeze is due to an absence of response and dbus ~25s timeout, I wonder if there is a way to get the extension to cancel a request if it takes more than say 0.5s (or even 1s to be safe) for the response to come through?

**Comment by Moon-0xff** [comment]
[Yes we can.](https://gjs-docs.gnome.org/gio20~2.66p/gio.dbusproxy#method-set_default_timeout)
But judging by how (mpris.js)[https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/mpris.js] handles things, i don't think it's necessary at all.

**Comment by Moon-0xff** [comment]
My theory is all the D-Bus stuff is handled by the proxy without slowing down or bothering the main thread **except** when it's declared.
If that's the case then simply adding a [function callback](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/mpris.js#L98) to the proxy declaration should solve this issue.

**Comment by Moon-0xff** [comment]
Well, i just did it. It doesn't seem to create any problem, but does it solve the issue?

**Comment by Batwam** [comment]
Only time will tell I guess. In the meantime, the latest changes vastly improved the cycle times so I'd suggest releasing this as the main version when you are comfortable.

**Comment by Moon-0xff** [comment]
There's a few things to do before a release. Mostly testing.
I will submit a "roadmap" for v5 soon enough.

**Comment by Moon-0xff** [comment]
Shortwave generates errors for GNOME mpris.js too
```
JS ERROR: Exception in callback for signal: hide: Error: Impossible to remove untracked message
                                        removeMessage@resource:///org/gnome/shell/ui/messageList.js:680:19
                                        _addPlayer/<@resource:///org/gnome/shell/ui/mpris.js:271:18
                                        _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                        _updateState@resource:///org/gnome/shell/ui/mpris.js:234:22
                                        _onPlayerProxyReady/<@resource:///org/gnome/shell/ui/mpris.js:183:48
```

**Comment by Moon-0xff** [comment]
[This latest version works well for the user that initially raised the issue](https://extensions.gnome.org/extension/4928/mpris-label/). Amazing!
Time to close this.
