### ISSUE TITLE
Feature request: Scrolling Text / Marquee

### ISSUE THREAD

**Issue by imjuzcy** [Moon-0xff/gnome-mpris-label#70]
An example from another GNOME extension [spotify-tray](https://github.com/esenliyim/sp-tray): 
![gif](https://github.com/esenliyim/sp-tray/blob/master/example_marquee.gif?raw=true) 

This would allow having a relative short max string length while being able to see all details.

**Comment by Moon-0xff** [comment]
Hi!

I'm not sure if we can add this without hurting maintainability. The [implementation](https://github.com/esenliyim/sp-tray/blob/master/panelButton.js) is rather complex and we are currently changing the *core* code of the extension.

I also personally don't like it.

However [spotify-tray](https://github.com/esenliyim/sp-tray) and this extension are based around the same object (`PanelMenu.button`), and they were [very similar before](https://github.com/esenliyim/sp-tray/issues/5) (probably they still are) so it might be possible to make it work by just pasting the code and tweaking it a bit.

I can't work on this, but if you or anyone else manages to make it work please share it! I probably wouldn't add it to the code but it might be possible to make a patch out of it.

**Comment by imjuzcy** [comment]
No problem! I don't have any experience developing GNOME extensions, so it might take some time for me to implement it. I might come back to it when I have the time to. 

In the meantime, I'll close this as unplanned, if I successfully implemented this I'll comment here.
