### ISSUE TITLE
Let customize cover height

### ISSUE THREAD

**Issue by muerwre** [Moon-0xff/gnome-mpris-label#71]
Please, add setting to customize icon height (or vertical paddings), so album cover won't take 100% of panel height. 

![g9](https://github.com/Moon-0xff/gnome-mpris-label/assets/33246675/318722fc-5c9e-4220-ad67-a7f4ffb7448c)

**Comment by Moon-0xff** [comment]
Icon height like the **"Album art scaling"** option?  
Vertical padding to off center the album art up or down?

I'm not sure what you mean.

**Comment by muerwre** [comment]
@Moon-0xff, sorry, updated issue description. The idea is to make cover look like other panel elements, like having margins and, maybe, a little border rounding.

**Comment by Moon-0xff** [comment]
Thanks for the visual aid! It looks like you want to reduce the value of the **"Album art scaling"** option. The default value is 60% to match with other elements in the panel, looks like yours is set to 100%.

And I like the idea of rounded corners, but I don't know if there's a good way of adding them (perhaps with CSS?).

**Comment by muerwre** [comment]
For me scale (now set to 50) only changes horizontal space around it (I'm on gnome-shell 44.3 btw). 

Rounding could be done with border-radius in CSS.

**Comment by Moon-0xff** [comment]
I suppose we should decrease the minimum allowed value of the **"Album art scaling"** option then.

What you are doing there is decreasing the value that **"Album art scaling"** sets by 8 pixels more (less?). Basically:
```js
icon_size: Math.floor(Main.panel.height*50/100) - 8;
```
The 50 comes from the **"Album art scaling"** setting.

It might be helpful to know what's your panel height. Can you run this command on the looking glass evaluator and show me the output?
```js
>>> Main.panel.height
```
To open looking glass:
1. `Alt+F2` or whatever your *"run command"* shortcut is
2. type `lg`

**Comment by muerwre** [comment]
>  Can you run this command on the looking glass evaluator and show me the output?
It's 64px, default for Manjaro gnome built-in theme, which is based in default, I suppose (?)

>  Math.floor(Main.panel.height*50/100) - 8
It's 24

**Comment by Moon-0xff** [comment]
Helpful! Math is the same. I don't know why the percentage needs to be so low but in any case we only need to decrease the minimum value of **"Album art scaling"** to solve this.

I will push an update soon enough. You will need to choose 39% to get the same value when the update comes:
```js
Math.floor(64 * 39 / 100)
```

**Comment by Moon-0xff** [comment]
Fix is already in `main`, just a one line diff.

I will update the extension when I have something else to add, I don't like to push small updates.

Thanks for raising this issue! I will close this when the next update is live.

**Comment by muerwre** [comment]
Thanks, it works as expected! Also, now 50% setting makes it the right size (on this picture I've tried to figure out how to make round corners on St.Icon, sadly without any luck, so, don't look at the red artifacts around it).

![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/33246675/5b147509-cbdf-41f6-b8d4-fb44cc928c43)

**Comment by Moon-0xff** [comment]
For sure I would love to know if you get the rounded borders working!

**Comment by Moon-0xff** [comment]
Update is live. Thanks again!
