### ISSUE TITLE
New name doesn't appear in Extension Manager

### ISSUE THREAD

**Issue by Batwam** [Moon-0xff/gnome-mpris-label#74]
Hi,

I don't know if it's only me but I noticed that the extension name no longer appears in [Extension Manager:](https://flathub.org/apps/com.mattjakeman.ExtensionManager)
![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/56710655/937858e2-8efa-4a8f-8517-fb92cb9ed284)

I remove the `&` from the name and it came back. 
![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/56710655/afed306d-5c70-4780-824c-ca6ff3fdfbe6)

Note that the issue doesn't appear in [Extensions](https://flathub.org/apps/org.gnome.Extensions):
![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/56710655/4556b9d4-cea8-46ec-9659-0354824a2e14)

So you could argue that it's an Extension Manager bug... which is why I also reported it here: https://github.com/mjakeman/extension-manager/issues/473

Depending in the outcome of the bug report, I'm just reporting it here so you are aware of the issue and in case you feel that we should remove the special character from the new name.

**Comment by Moon-0xff** [comment]
Well, this is an issue with Extension Manager, not with our extension.  
Also, Extension Manager is a third party app, not a GNOME one.

I would prefer to ignore this issue. It doesn't set a good precedent.

But Extension Manager is to my knowledge widely used, so I think making a workaround for it is justified.

**Comment by Moon-0xff** [comment]
Solved in dfe17b3a4b3d0429c38e240205f372e0c4960132.
