### ISSUE TITLE
Port to GNOME 45

### ISSUE THREAD

**Issue by Moon-0xff** [Moon-0xff/gnome-mpris-label#77]
GNOME 45 introduces a lot of *structural* changes that will require a considerable amount of work.  
These changes are not reconcilable with >45, which is a problem, and poses a lot of questions.

https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by Batwam** [comment]
ah, I was just reading this page and was about to post this exact same link here! yeah, this tendency to break things with upgrades is getting frustrating...

**Comment by Moon-0xff** [comment]
Gnome relies solely on the mpris desktop entry to match the app.
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/mpris.js?ref_type=heads#L228

**Comment by Batwam** [comment]
Ah, you just crushed my hopes! 

on the Gnome 45 compatibility front, I'll most likely switch next month. For some reason, gnome-nightly won't install on gnome-boxes for me anymore (looks like I'm not alone). We could always try with Fedora rawhide. are we possibly going to have 2 versions going forward since the gnome 45 version won't be backwards compatible?

**Comment by Moon-0xff** [comment]
> are we possibly going to have 2 versions going forward since the gnome 45 version won't be backwards compatible?

I want to target 43, 44 **and** 45. To do that 2 versions of the extension will have to be uploaded to ego. [ego supports multi-versioning](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#shell-version) so at least there's that.

The problem is, maintaining two versions of the same software isn't trivial, and dealing with diverging branches isn't fun.

It *might* be possible to deal with the version differences painlessly with a patch file, but I really don't know. For the meantime I would prefer to simply ignore 45 until it hits major distributions.

**Comment by Batwam** [comment]
yeah, EGO allows multiple versions but that means that we (you) need to upload two versions and every file will be changed slightly which is a pain. I was wondering if the gnome 45 version could be `main` with the gnome 42/43/44 compatible as a fork (or vice versa). This way, if make changes, we can simply use git to sync the fork (assuming the changes don't break it). 

Will you be switching to gnome 45 anytime soon? I will likely be on it from next month.

**Comment by Moon-0xff** [comment]
> This way, if make changes, we can simply use git to sync the fork (assuming the changes don't break it).

I don't expect an automated work when doing it that way, specially because we include a binary file on the version control.

> Will you be switching to gnome 45 anytime soon?

Not at all. Though I can always spin-up a VM.

**Comment by Batwam** [comment]
Yeah, I was somewhat relying on the fact that the binary file doesn't really change that often and might be common between both versions?

**Comment by Moon-0xff** [comment]
[GNOME 45 is starting to hit major distributions](https://repology.org/project/gnome-shell/versions).

**Comment by Batwam** [comment]
With the inclusion of the diff file, I consider that this is completed on my end so I'm not doing any further work on this. Let me know if you find any bug.

I assume that you will be testing the gnome45 version in due course, merge with `main` and upload to EGO in due course?

**Comment by Moon-0xff** [comment]
I failed to communicate this but I gave you collaborator access because I'm starting to get busy and I will not be able to attend this project with the attention it needs.

If you can test the 45 version and be confident it works reliably, let me know and I will push an update, though I'm not sure how the multi-versioning on ego works.  
If not I'll try to get it done the next week.

I already merged `45-as-patch` with `main` by the way.

**Comment by Moon-0xff** [comment]
For the reader interested on installing the 45 version earlier, the installation script patches the extension if it detects a gnome-shell version above or equal to 45. [Here's the installation instructions (using the script).](https://github.com/Moon-0xff/gnome-mpris-label#using-git-and-the-installation-script)

**Comment by Batwam** [comment]
I have just upgraded to gnome 45 and everything is working as expected for me.

**Comment by Moon-0xff** [comment]
Alright, I'll upload the 45 version to ego then!

**Comment by Moon-0xff** [comment]
Update was accepted and is live on ego.

Here's a link to the review: https://extensions.gnome.org/review/46459  
And to the extension: https://extensions.gnome.org/extension/4928/mpris-label/

I will close this issue now.

**Comment by Batwam** [comment]
Excellent! I guess we are  on version 26 now then?
