### ISSUE TITLE
Suggestion: Modify the scrolling control volume direction

### ISSUE THREAD

**Issue by WhoChangedMyCode** [Moon-0xff/gnome-mpris-label#89]
In the "Controls" of the "Scroll up/down", the current situation is that scrolling up is to lower the volume, scrolling down is to raise the volume, I think this is not in line with the intuitive operation, especially when I use the touchpad of the notebook, the result of the volume control is always the reverse of my first intuitive operation, maybe I am a different kind of bar.

I hope to have some improvement:
Scrolling up is to increase the volume, scrolling down is to decrease the volume. Or add a new option for the user to choose whether scrolling up raises the volume or lowers it.

**Comment by Moon-0xff** [comment]
I also noticed the touchpad gesture to raise/lower volume is reversed. But this is consistent with the global volume widget, and I think the rest of GNOME.

It's a simple change to add though, on `extension.js`:
```js
			case 'volume-up':
				this._changeVolume(1); /* CHANGE THIS TO -1 */
				break;
			case 'volume-down':
				this._changeVolume(-1); /* CHANGE THIS TO 1 */
				break;
			case 'volume-mute':
				this._changeVolume(0);
				break;
		}
	}

	_changeVolume(delta){ /* MULTIPLY delta BY -1 */
		let stream = [];
		stream[0] = this.volumeControl.get_default_sink();
		let streamName = 'System Volume (Global)';

		const CONTROL_SCHEME = this.settings.get_string('volume-control-scheme');
```

**Comment by Batwam** [comment]
agreed with keeping the scroll volume control consistent between the extension and the global volume widget. I just checked and changed from "Traditional" to "Natural" and they both inverted so that's the correct behaviour in my view.

**Comment by Moon-0xff** [comment]
Alright. I will close this as unplanned.

As mentioned: You can modify the source code to do this (just follow the comments I left on my previous comment).
